export const Routes = {
    Home: "/",
    
    Research: "/about",
    Careers: "/about",
    FAQ: "/faq",
    Contact: "/contact",
    JoinUs: "/about",

    Difference: "/#difference",
    Workflow: "/#workflow",
    Capabilities: "/#capabilities",
    Integrations: "/#integrations",
    Membership: "/#membership",

    Learn: "/learn",
    LearnDoc: (doc: string) => `/learn/${doc}`,
    LearnUnits: "/learn",
    LearnUnitEdition: (unitSlug: string, year: number | string) => `/learn`,
    Challenges: "/learn",
    Gallery: "/about",

    Surveys: "/surveys",
    Survey: (id: string) => `/surveys/${id}`,
    Trivia: "/learn",
    TriviaSet: (id: string) => `/learn/${id}`,
    Articles: "/learn",
    Article: (slug: string) => `/learn/${slug}`,
    Knowledge: "/learn",
    KnowledgeEntry: (id: string) => `/learn/${id}`,
    Events: "/events",
    Event: (id: string) => `/events/${id}`,

    Login: "/auth/login",
    Register: "/auth/register",
    Verify: "/auth/verify",
    Reset: "/auth/reset",
    Invite: "/auth/register",
    Account: "/account",
    AccountNotifications: "/account/notifications",
    AccountSignOut: "/account/sign-out",
} as const;