export const Routes = {
    Home: "/",
    
    Research: "/about",
    Careers: "/about",
    FAQ: "/faq",
    Contact: "/contact",
    JoinUs: "/auth/register",

    Difference: "/#difference",
    Workflow: "/#workflow",
    Capabilities: "/#capabilities",
    Integrations: "/#integrations",
    Membership: "/#membership",

    Learn: "/learn",
    LearnVideos: "/learn/videos",
    LearnArticles: "/learn/articles",
    LearnStories: "/learn/stories",
    LearnDocuments: "/learn/documents",
    LearnPaths: "/learn",
    LearnPath: (slug: string) => `/learn/paths/${slug}`,
    LearnQuests: "/learn/quests",
    LearnProfile: "/learn/profile",
    LearnDoc: (doc: string) => `/learn/${doc}`,
    LearnUnits: "/learn",
    LearnUnitEdition: (unitSlug: string, year: number | string) => `/learn/units/${unitSlug}/${year}`,
    Challenges: "/learn/quests",
    Gallery: "/about",

    Surveys: "/surveys",
    Survey: (id: string) => `/surveys/${id}`,
    Trivia: "/learn",
    TriviaSet: (id: string) => `/learn/${id}`,
    Articles: "/learn",
    Article: (slug: string) => `/learn/${slug}`,
    Knowledge: "/learn",
    KnowledgeEntry: (id: string) => `/learn/${id}`,
    Events: "/events",
    Event: (id: string) => `/events/${id}`,

    Login: "/auth/login",
    Register: "/auth/register",
    Verify: "/auth/verify",
    Reset: "/auth/reset",
    Invite: "/auth/register",
    Account: "/learn/account",
    AccountPassword: "/learn/account/password",
    AccountNotifications: "/learn/account/notifications",
    AccountSignOut: "/learn/account/sign-out",
} as const;