"use client";

import Link from "next/link";
import Image from "next/image";
import {
  ArrowLeft,
  Film,
  ShieldCheck,
  TrendingUp,
  ArrowUpRight,
  ExternalLink,
} from "lucide-react";
import { EditorialPill } from "@/components/ui/editorial/editorial-pill";
import { PillButtonGroup } from "@/components/ui/editorial/pill-button-group";
import { BNS_MEDIA_IMAGES } from "@/constants/bns-media-images";
import { SECTION_SHELL_INNER } from "@/layouts/section-shell";
import {
  TelemetryHUD,
  MaskedReveal,
  ParallaxWrapper,
  MetricCounter,
  NarrativeScrollytellingCanvas,
  type NarrativeBeat,
  CinemaTimelineStage,
} from "@/components/motion";

const STUDIOS_BEATS: NarrativeBeat[] = [
  {
    id: "donor-trap",
    eyebrow: "The Strategic Friction",
    title: "Breaking the 12-month donor cycle with sovereign revenue.",
    paragraphs: [
      "Most civic watchdog organizations in Africa exist on a fragile treadmill of annual donor grants. When foreign funding priorities pivot or grant cycles expire, critical budget tracking operations suddenly vanish, leaving government ministries unchecked.",
      "Budget Ndio Story refused this dependency. We engineered Desk 04 — BNS Studios — as an independent, high-grade creative production house. We sell top-tier videography, podcast engineering, 2D motion graphics, and town hall broadcasts to commercial and institutional partners.",
      "The governing covenant is unalterable: 100% of operating surplus generated by BNS Studios is plowed directly into funding grassroots audit scorecards, newsroom fellowships, and rural barazas in all 47 counties.",
    ],
    quote: {
      text: "If your budget scrutiny depends on foreign grant approval, your watchdog is on a leash. True civic independence requires sovereign financial resilience.",
      author: "BNS Commercial Desk",
      role: "Nairobi Studio",
    },
    metric: {
      value: "100%",
      label: "Commercial Surplus Reinvested",
    },
    image: BNS_MEDIA_IMAGES.productionA,
    imageAlt: "BNS Studio production crew filming investigative field segments",
    imageCaption: "BNS Studios field camera unit filming community testimonies in Western Kenya.",
    imageBadge: "SOVEREIGN SURPLUS ENGINE",
  },
  {
    id: "high-craft",
    eyebrow: "The Creative Method",
    title: "We don't publish 200-page reports nobody reads. We produce media people share.",
    paragraphs: [
      "Bureaucratic institutions have spent millions producing dry PDF reports that gather dust on web servers while citizens make voting decisions based on WhatsApp rumors. Opacity thrives when truth is boring.",
      "BNS Studios applies cinema-grade storytelling standards to complex fiscal balance sheets. We shoot in anamorphic 21:9 aspect ratios, compose original Swahili audio soundscapes, and design motion graphics that turn 40-page debt amortizations into 60-second video feeds.",
      "When our flagship explainer 'Budget Sasa ni Delivery' dropped, it crossed 480,000 views within 90 days across YouTube and social feeds — without spending a single shilling on synthetic ad scaling.",
    ],
    quote: {
      text: "Nobody shares a procurement audit PDF on TikTok. But when you turn that audit into a 45-second motion reel with verified figures, millions pay attention.",
      author: "Nelly Maina",
      role: "Host, Budget Ndio Story Podcast",
    },
    metric: {
      value: "480K+",
      label: "Views on Flagship Explainer",
    },
    image: "/images/marketing newsletter subcribe/Nelly with The Mic.jpg",
    imageAlt: "Podcast recording session with microphone and studio lighting",
    imageCaption: "In-studio recording of the Budget Ndio Story Podcast Season 01.",
    imageBadge: "PODCAST & AUDIO SCRUTINY",
  },
  {
    id: "double-impact",
    eyebrow: "The Double Impact Covenant",
    title: "Every commissioned shilling bankrolls an audit in Kilifi, Nakuru, or Wajir.",
    paragraphs: [
      "When a development bank, civil society coalition, or government agency commissions BNS Studios for a multi-camera town hall or documentary series, they receive broadcast-quality production while directly bankrolling public accountability.",
      "A single commercial documentary contract pays for the printing of 5,000 waterproof budget scorecards for artisanal fisherfolk in Kilifi County, and provides monthly stipends for youth field trackers in Wajir.",
      "This circular economic model has allowed Budget Ndio Story to expand across 47 counties without compromising its editorial independence or partisan neutrality.",
    ],
    metric: {
      value: "47",
      label: "Counties Subsidized by Studio Surplus",
    },
    image: "/images/hall/129A4248.jpg",
    imageAlt: "Multi-camera hall production at National Stakeholder Forum",
    imageCaption: "Multi-camera live broadcast setup at the National Stakeholder Fiscal Forum.",
    imageBadge: "BROADCAST & TOWN HALL PRODUCTION",
  },
];

export function StudiosScrollytelling() {
  return (
    <article className="min-h-screen bg-background text-foreground selection:bg-primary/20">
      {/* 00 — PERSISTENT LOCOMOTIVE-GRADE TECHNICAL HUD */}
      <TelemetryHUD
        activeDesk="DESK 04: BNS STUDIOS"
        focusArea="COMMERCIAL CRAFT & REINVESTMENT"
        badgeLabel="SOVEREIGN COVENANT"
      />

      {/* 01 — CINEMATIC MIDNIGHT MASTHEAD HERO */}
      <header className="relative border-b border-border/40 bg-gradient-to-b from-primary/10 via-muted/10 to-background pt-4 pb-6 md:pt-6 md:pb-8 overflow-hidden">
        <div className={SECTION_SHELL_INNER}>
          {/* Breadcrumb back to programmes */}
          <nav aria-label="Breadcrumb" className="mb-3">
            <Link
              href="/programmes"
              className="inline-flex items-center gap-2 text-xs font-mono font-bold uppercase tracking-wider text-muted-foreground transition-colors hover:text-foreground"
            >
              <ArrowLeft className="size-3.5" />
              <span>All Operational Desks</span>
            </Link>
          </nav>

          <div className="space-y-4 max-w-5xl">
            <div className="flex flex-wrap items-center gap-2">
              <EditorialPill dot pulse>
                Desk 04 · Commercial Creative Craft
              </EditorialPill>
              <EditorialPill variant="outline">
                The Sovereign Reinvestment Model
              </EditorialPill>
            </div>

            <h1 className="font-heading text-4xl sm:text-6xl lg:text-7xl font-black tracking-tight text-foreground leading-[1.02]">
              <MaskedReveal delay={0.05}>Commercial creative craft</MaskedReveal>{" "}
              <MaskedReveal delay={0.15}>that bankrolls citizen</MaskedReveal>{" "}
              <MaskedReveal delay={0.25} innerClassName="text-primary">
                budget audits.
              </MaskedReveal>
            </h1>

            <p className="text-xl sm:text-2xl font-medium text-foreground/80 leading-relaxed max-w-3xl">
              We operate an independent, broadcast-grade production studio delivering podcasts, documentaries, 2D motion graphics, and town hall broadcasts for institutional partners. 100% of operating surplus is channeled into grassroots watchdog operations across all 47 counties.
            </p>

            {/* Strategic Overview Strip */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-6 pt-6 border-t border-border/50">
              <div className="space-y-1">
                <p className="text-[11px] font-mono font-bold uppercase tracking-wider text-muted-foreground">
                  Economic Model
                </p>
                <p className="text-base font-bold text-foreground">
                  Sovereign Enterprise
                </p>
                <p className="text-xs text-muted-foreground">Zero Donor Dependency</p>
              </div>

              <div className="space-y-1">
                <p className="text-[11px] font-mono font-bold uppercase tracking-wider text-muted-foreground">
                  Surplus Covenant
                </p>
                <p className="text-base font-bold text-primary">
                  100% Reinvested
                </p>
                <p className="text-xs text-muted-foreground">Scorecards & Fellowships</p>
              </div>

              <div className="space-y-1">
                <p className="text-[11px] font-mono font-bold uppercase tracking-wider text-muted-foreground">
                  Production Formats
                </p>
                <p className="text-base font-bold text-foreground">
                  <MetricCounter value={3} suffix=" Disciplines" />
                </p>
                <p className="text-xs text-muted-foreground">Podcasts, Docs, Motion</p>
              </div>

              <div className="space-y-1">
                <p className="text-[11px] font-mono font-bold uppercase tracking-wider text-muted-foreground">
                  Commercial Portal
                </p>
                <Link
                  href="/bns-studio"
                  className="text-base font-bold text-primary hover:underline inline-flex items-center gap-1"
                >
                  <span>Open Studio</span>
                  <ArrowUpRight className="size-3.5" />
                </Link>
                <p className="text-xs text-muted-foreground">Client Intake & Theatre</p>
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* 02 — THE NARRATIVE SCROLLYTELLING CANVAS & CINEMA TIMELINE */}
      <section className="border-b border-border/40 pb-16">
        <div className={SECTION_SHELL_INNER}>
          <NarrativeScrollytellingCanvas beats={STUDIOS_BEATS} mediaPosition="right" />

          {/* Interactive Cinema Timeline & 8-Format Production Spectrum */}
          <CinemaTimelineStage />
        </div>
      </section>

      {/* 03 — COMMERCIAL INTAKE CALLOUT BAND */}
      <section className="py-16 md:py-24">
        <div className={SECTION_SHELL_INNER}>
          <div className="rounded-3xl bg-zinc-950 text-white p-8 sm:p-12 md:p-16 border border-zinc-800 relative overflow-hidden">
            <div className="absolute top-0 right-0 w-96 h-96 bg-primary/20 blur-3xl rounded-full pointer-events-none" />

            <div className="max-w-2xl space-y-4 relative z-10">
              <span className="text-xs font-mono font-bold uppercase tracking-widest text-primary">
                Commission BNS Studios
              </span>
              <h2 className="text-3xl sm:text-5xl font-black tracking-tight leading-tight">
                Commission high-craft media. Bankroll sovereign accountability.
              </h2>
              <p className="text-zinc-300 text-base sm:text-lg leading-relaxed">
                Whether you need an 8-episode podcast series, a nationwide town hall broadcast, or 2D motion graphics explaining complex policy reforms — BNS Studios delivers verified broadcast quality.
              </p>

              <div className="pt-4 flex flex-col sm:flex-row items-stretch sm:items-center gap-3">
                <PillButtonGroup
                  href="/bns-studio"
                  label="Commission the Studio"
                  variant="primary"
                  className="w-full sm:w-auto justify-center"
                />
                <PillButtonGroup
                  href="/work"
                  label="Explore Production Archive"
                  variant="outline"
                  className="hidden sm:inline-flex w-full sm:w-auto justify-center border-zinc-700 text-white hover:bg-zinc-900"
                />
              </div>
            </div>
          </div>
        </div>
      </section>
    </article>
  );
}
